package packets

const PACKET_UNKNOWN = "???"
const PACKET_EVENT = "EVENT"
const PACKET_REQUEST = "REQ"
const PACKET_RESPONSE = "RES"
const PACKET_DISCOVER = "DISCOVER"
const PACKET_INFO = "INFO"
const PACKET_DISCONNECT = "DISCONNECT"
const PACKET_HEARTBEAT = "HEARTBEAT"
const PACKET_PING = "PING"
const PACKET_PONG = "PONG"

const PACKET_GOSSIP_REQ = "GOSSIP_REQ"
const PACKET_GOSSIP_RES = "GOSSIP_RES"
const PACKET_GOSSIP_HELLO = "GOSSIP_HELLO"
